/* eslint-disable @next/next/no-img-element */
import React from "react";
import Head from "next/head";
import style from "@/styles/pages/filterStyle.module.scss";
import Link from "next/link";
import Navbar from "@/components/organisms/navbar";
import CardProduct from "@/components/molecules/cardContent";
import Footer from "@/components/organisms/footer";

import {
  Avatar,
  AppBar,
  Box,
  Toolbar,
  IconButton,
  Typography,
  InputBase,
  Badge,
  MenuItem,
  Menu,
  Card,
  CardContent,
  CardMedia,
  Modal,
  Button,
  TextField,
  Grid,
  Breadcrumbs,
  CircularProgress,
  CardActionArea,
  Rating,
  Pagination,
} from "@mui/material";
import { Router } from "next/router";
import CardProductContent from "@/components/molecules/cardContent";

export default function SelectedCategories() {
  const capitalize = (str) => {
    return str.replace(/(^\w|\s\w)/g, function (letter) {
      return letter.toUpperCase();
    });
  };

  const convertNumber = (str) => {
    return str.replace(/\d(?=(\d{3})+$)/g, "$&.");
  };

  return (
    <>
      <Head>
        <title>Selected Categories | Tuku</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/images/logo.png" />
      </Head>
      <main>
        <Navbar />

        <Box flex={4} p={{ xs: 4, md: 8 }}>
          <>
            <Breadcrumbs aria-label="breadcrumb">
              <Link underline="hover" color="inherit" href="/">
                Home
              </Link>
              <Typography color="text.primary">Categories</Typography>
            </Breadcrumbs>
            <Grid
              container
              spacing={1}
              sx={{
                mt: 2,
                display: "flex",
                justifyContent: "center",
              }}>
              {!sessionStorage.getItem("categoriesData") ? (
                <Typography variant="h4" sx={{ marginTop: "100px" }}>
                  Product not available
                </Typography>
              ) : (
                <>
                  {JSON.parse(sessionStorage.getItem("categoriesData"))?.map(
                    (product, index) => (
                      <CardProductContent key={index} data={product} />
                    )
                  )}
                </>
              )}
            </Grid>
          </>
        </Box>
      </main>
    </>
  );
}
